### ISSUE TITLE
[Bug] Refresh of files after a delete

### ISSUE THREAD

**Issue by Te-Z** [linagora/twake-drive-legacy#601] opened 2024-07-22 09:20 UTC
**Describe the bug**

When a file is deleted the files list refresh but some files and folders disappear
Tested on Chrome https://drive.stg.lin-saas.com/

**To Reproduce**
- delete a file

Some files & folders disappear. User has to refresh screen to see everything

**Expected behavior**

All not deleted files are displaying on the screen

**Screenshots**

[Capture vidéo du 22-07-2024 11:15:22.webm](https://github.com/user-attachments/assets/9358b1fc-a53c-45c8-9e87-70e72aa3505a)

**Comment by shepilov** [comment] 2024-07-22 13:14
duplicate of #588

**Closed as completed by shepilov** 2024-07-22 13:14 UTC
Labels: bug
